/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noted_prototype;


public class Spoiler extends javax.swing.JPanel {

     boolean collapsed = false;
     int paneSize = 0;
     
    /**
     * Creates new form Spoiler
     */
    public Spoiler() {
        initComponents();
        setVisible(true);
        ExpandCollapseCodeButton.setVisible(true);
        jScrollPane1.setVisible(true);
        spoilerText.setVisible(true);
        titleField.setVisible(true);
        setSize(100,100);
        paneSize = jScrollPane1.getHeight();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExpandCollapseCodeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        spoilerText = new javax.swing.JTextArea();
        titleField = new javax.swing.JTextField();

        ExpandCollapseCodeButton.setText("Hide");
        ExpandCollapseCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpandCollapseCodeButtonActionPerformed(evt);
            }
        });

        spoilerText.setColumns(20);
        spoilerText.setRows(5);
        spoilerText.setPreferredSize(new java.awt.Dimension(800, 94));
        jScrollPane1.setViewportView(spoilerText);

        titleField.setText("New Hide/Show Box");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleField, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExpandCollapseCodeButton))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpandCollapseCodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExpandCollapseCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpandCollapseCodeButtonActionPerformed
        if (collapsed == false){
            spoilerText.setVisible(false);
            jScrollPane1.setVisible(false);
            ExpandCollapseCodeButton.setText("Show");
            collapsed = true;
            jScrollPane1.setSize(jScrollPane1.getWidth(), 1);
            setSize(getWidth(), getHeight() - paneSize);
        } else {
            spoilerText.setVisible(true);
            jScrollPane1.setVisible(true);
            ExpandCollapseCodeButton.setText("Hide");
            collapsed = false;
            jScrollPane1.setSize(jScrollPane1.getWidth(), paneSize);
            setSize(getWidth(), getHeight() + paneSize);
        }
    }//GEN-LAST:event_ExpandCollapseCodeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExpandCollapseCodeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea spoilerText;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
